version: '3.8'

services:
  # Сервис для разработки с горячей перезагрузкой
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: csv-data-processor-dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Сервис для продакшена
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csv-data-processor-prod
    ports:
      - "80:80"
    restart: unless-stopped 